# Generated by Django 4.2.14 on 2025-07-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.TextField(blank=True, max_length=500)),
                ('description', models.CharField(choices=[('گازی', 'gazi'), ('برقی', 'barghi')], max_length=50)),
                ('image', models.URLField(blank=True, default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png')),
                ('catalog', models.URLField(blank=True, default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png')),
            ],
        ),
    ]
