# Generated by Django 4.2.14 on 2025-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_item_category_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalog',
            field=models.ImageField(blank=True, default='media/catalogs/default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='media/products/default.png', upload_to='media/'),
        ),
    ]
